name: Checkout Example

on: push

jobs:
  checkout-demo:
    runs-on: windows-latest
    steps:
      - name: Check Versions
        run: |
          dotnet --version
          node --version
          git --version
